version: 2
updates:
- package-ecosystem: nuget
  directory: "/Rebus.CastleWindsor"
  schedule:
    interval: daily
    time: "04:00"
- package-ecosystem: nuget
  directory: "/Rebus.CastleWindsor.Tests"
  schedule:
    interval: daily
    time: "04:00"
