image: Visual Studio 2019

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.CastleWindsor -c Release
  - dotnet build Rebus.CastleWindsor.Tests -c Release

test_script:
  - dotnet test Rebus.CastleWindsor.Tests --no-build --verbosity normal -c Release
